In [1]:
import numpy as np
import scipy
import scipy.linalg

In [2]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, -5, 0], [11, 4, 7]])
print(A)

[[ 1  2 -1]
 [ 3 -4  0]
 [ 8 -5  2]
 [ 2 -5  0]
 [11  4  7]]


In [3]:
B = np.array([[1, 7, 12, 7, 15]])
print(B)

[[ 1  7 12  7 15]]


In [5]:
np.linalg.lstsq(A,B.T)


<ipython-input-5-ba2d7c6fe157>:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A,B.T)


(array([[ 1.36567907],
        [-0.49037687],
        [ 0.18895473]]),
 array([8.29412183]),
 3,
 array([15.62003532,  9.55109208,  1.94708413]))

In [ ]:
#если не брать B.T, то вываливатся ошибка: "Incompatible dimensions"
#полагаю, что здесь при решении очень важна размерность матриц (векторов)