In [38]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#проверим, является ли система уравнений совместной.
#в зависимости от этого будем выбирать способ ее решения
#обозначим А - матрицу коэффициентов, В - матрицу свободных членов, С - расширенную матрицу
#вычислим определитель системы
#сравним ранг матрицы коэффициентов и матрицы свободных членов

In [17]:
np.linalg.det(a)

array([[54.]])

In [39]:
A = np.array([[1, 2, 3],[4, 0, 5], [7, 8, 9]])
B = np.array([[12, 2, 1]])
C = np.concatenate((A, B.T), axis=1)
r = np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)
print(C)
print(r)

[[ 1  2  3 12]
 [ 4  0  5  2]
 [ 7  8  9  1]]
(3, 3)


In [ ]:
#на основании полученных результатов делаем вывод, 
#что система совместна и имеет единственное решение

In [43]:
np.linalg.solve(a,b)

array([-8.48148148, -0.53703704,  7.18518519])

In [44]:
np.linalg.solve(A, B.T)

array([[-8.48148148],
       [-0.53703704],
       [ 7.18518519]])