In [78]:
import numpy as np
import scipy
import scipy.linalg

In [ ]:
#проверим, является ли система уравнений совместной.
#обозначим А - матрицу коэффициентов, В - матрицу свободных членов, С - расширенную матрицу
#вычислим определитель системы
#сравним ранг матрицы коэффициентов и матрицы свободных членов

In [79]:
A = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
B = np.array([[12, 2, 1]])

In [80]:
np.linalg.det(A)

6.66133814775094e-16

In [81]:
C = np.concatenate((A, B.T), axis=1)
r = np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)
print(C)
print(r)


[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]
(2, 3)


In [ ]:
#ранг А и ранг С отличны друг от друга - система не имеет решений
#изменим вектор B - вектор D

In [82]:
D = np.array([[0, 0, 0]])
print(D)

[[0 0 0]]


In [83]:
C = np.concatenate((A, D.T), axis=1)
r = np.linalg.matrix_rank(C, 0.0001)
print(C)
print(r)

[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]
2


In [85]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [84]:
np.linalg.solve(A, D.T)

array([[0.],
       [0.],
       [0.]])