In [1]:
import numpy as np
import scipy
import scipy.linalg

In [29]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
print(A)

[[ 1  2  3]
 [ 2 16 21]
 [ 4 28 73]]


In [32]:
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [36]:
#проверю правильность разложения
W = np.dot(P,np.dot(L,U))
print(W)

[[ 1.  2.  3.]
 [ 2. 16. 21.]
 [ 4. 28. 73.]]


In [38]:
#придумаем вектор свободных членов В
B = np.array([[1, 7, 0]])

In [ ]:
#решим систему с помощью разложения:
#A*x = L*U = B

In [40]:
np.linalg.solve(A,B.T)

array([[ 0.33796296],
       [ 0.84490741],
       [-0.34259259]])