In [9]:
import numpy as np
import scipy
import scipy.linalg

In [10]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
B = np.array([[2, 5, 11]])
print(B)

[[ 2  5 11]]


In [14]:
np.linalg.lstsq(A,B.T)


<ipython-input-14-ba2d7c6fe157>:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A,B.T)


(array([[ 1.25],
        [ 0.5 ],
        [-0.25]]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]))

In [ ]:
#если не брать B.T, то вываливатся ошибка: "Incompatible dimensions"
#полагаю, что здесь при решении очень важна размерность матриц (векторов)